### ISSUE TITLE
TODO prelaunch

### ISSUE THREAD

**Issue by rachelbasse** [rachelbasse/rachelbasse.github.io#1]
- [x] Make first stupid commit to test the things already!
- [ ] Main files to edit
  - [x] \_config.yml
  - [ ] README.md
  - [x] .gitignore - ignore images or not?
  - [x] ~~CONTRIBUTING.md~~
  - [x] ~~ISSUE_TEMPLATE.md~~
  - [x] 404.html/md
- [x] add home list
  - [x] add links for tags
- [x] add navigation
  - [x] pages
  - [x] tags
  - [x] social
- [x] add tag links, lists
- [x] add pages
- [x] ~~add pagination~~
- [x] add years for pagination
- [x] ~~redo timer images to be transparent~~
- [x] fix preview not running through markdown
- [x] add years menu to bottom
- [x] Convert handlebars to liquid
- [x] Import posts from json
  - [x] Replace cloudinary links
- [x] figure out where rss feed is
- [ ] Change domain, CNAME file
- [x] Move cloudinary to /images, change links
- [x] Test emojithings. :muscle: :balloon: :punch:
